/*
 * DO NOT EDIT THIS FILE
 *
 * It will be automatically generated from
 * templates defines in ./gulpfile.js
 * any time the templates are updated
 *
 */

// Define and set up utilities

var Utils = function() {};

Utils.prototype.createLogEntry = function(tab) {
  if (!tab) {
    return;
  }

  // ignore empty tabs and chrome settings pages
  var protocol = utils.getUrlProtocol(tab.url);
  if (protocol === 'chrome' || protocol === 'chrome-devtools') {
    return;
  }

  var previousEntry = _.find(logEntries, function(entry) {
    return tab.url === entry.url && tab.id === entry.tabId && tab.windowId === entry.windowId;
  });
  if (previousEntry) {
    console.log('Entry exists, skipping creation and adding a timestamp');
    if (previousEntry.ownIp === undefined) {
      previousEntry.getOwnGeo();
    }
    if (previousEntry.ip === undefined) {
      previousEntry.getRemoteGeo(previousEntry.domain);
    }
    previousEntry.addTimestamp();
    return;
  }

  var timestamp = new Date();
  logEntries.push(new LogEntry(tab.url, timestamp, tab.id, tab.windowId));

  var logEntry = new LogEntry();
  logEntry.storeEntries(logEntries);
  console.log('Created a new LogEntry');
};

Utils.prototype.findLogEntry = function(url, tabId, windowId) {
  var selected = _.find(logEntries, function(entry) {
    return url === entry.url && parseInt(tabId) === entry.tabId && parseInt(windowId) === entry.windowId;
  });
  return selected;
};

Utils.prototype.trimUrl = function(url) {
  var uri = new URI(url);
  var path = uri.hostname();
  return path;
};

Utils.prototype.getUrlProtocol = function(url) {
  var uri = new URI(url);
  var protocol = uri.protocol();
  return protocol;
};

Utils.prototype.log = function(thing) {
  console.log(thing);
};

Utils.prototype.get = function(url, callback) {
  var xhr = new XMLHttpRequest();
  xhr.open('GET', url, true);
  xhr.onreadystatechange = function() {
    if (xhr.readyState == 4 && xhr.status == 200) {
     callback(xhr.responseText);
    } else if (xhr.readyState == 4) {
      console.log('Error getting response data from ' + url);
    }
  }
  xhr.send();
};

Utils.prototype.reset = function() {
  logEntries = [];
  countryLog.reset();
  geoCache = new GeoCache();
  console.log('Erased browsing data');
};

// Define the LogEntry class

var LogEntry = function(url, timestamp, tabId, windowId) {
  if (url) {
    this.url = url;
    this.domain = utils.trimUrl(url);
    this.timestamps = [timestamp];
    this.tabId = tabId;
    this.windowId = windowId;
    this.getOwnGeo();
    this.getRemoteGeo(this.domain);
  }
};

LogEntry.prototype.fromJSON = function(json) {
  var that = this;
  _.each(json, function(value, key) {
    that[key] = value;
  });
  return this;
};

LogEntry.prototype.toJSON = function() {
  return JSON.prune(this);
};

LogEntry.prototype.latestTimestamp = function() {
  return _.max(this.timestamps);
};

LogEntry.prototype.addTimestamp = function() {
  var timestamp = new Date();
  this.timestamps.push(timestamp);
};

LogEntry.prototype.storeEntries = function(entries) {
  var logEntries = _.map(entries, function(entry) {
    return entry.toJSON();
  });
  storage.set({ 'logEntries': logEntries });
};

LogEntry.prototype.getOwnGeo = function() {
  storage.get('ownGeoData', _.bind(function(result) {
    // we try to retrieve the stored location
    var emptyResult = _.isEmpty(result);

    if (emptyResult) {
      // if there isn’t one we need to fetch it
      geoCache.addOwnLocation(this);
    } else {
      var ownGeoData = result.ownGeoData;
      var ownLocation = geoCache.getOwnLocation();

      // but if we have a new one we should use that
      if (ownLocation.ownIp) {
        ownGeoData = ownLocation;
      }

      if (ownGeoData.ownIp) {
        this.ownIp = ownGeoData.ownIp;
        this.ownCountryCode = ownGeoData.ownCountryCode;
        this.ownCountryName = ownGeoData.ownCountryName;
        this.ownRegionCode = ownGeoData.ownRegionCode;
        this.ownRegionName = ownGeoData.ownRegionName;
        this.ownTimezone = ownGeoData.ownTimezone;
        this.ownZipcode = ownGeoData.ownZipcode;
        this.ownCity = ownGeoData.ownCity;
        this.ownLat = ownGeoData.ownLat;
        this.ownLng = ownGeoData.ownLng;
        console.log('Using cached own geo');
        this.storeEntries(logEntries);
      } else {
        console.log('No own geo data available yet');
      }

    }
  }, this));
};

LogEntry.prototype.getRemoteGeo = function(domain) {
  if (domain === undefined) {
    console.log('can’t geolocate without a domain');
    return;
  }

  var cachedEntry = geoCache.hasEntry('domain', domain);
  if (cachedEntry && cachedEntry.ip) {
    this.ip = cachedEntry.ip;
    this.countryCode = cachedEntry.countryCode;
    this.countryName = cachedEntry.countryName;
    this.regionCode = cachedEntry.regionCode;
    this.regionName = cachedEntry.regionName;
    this.timezone = cachedEntry.timezone;
    this.zipcode = cachedEntry.zipcode;
    this.city = cachedEntry.city;
    this.lat = cachedEntry.lat;
    this.lng = cachedEntry.lng;
    countryLog.addVisit(this.countryCode);
    console.log('Retrieving entry details from cache');
    this.storeEntries(logEntries);
  } else {
    utils.get('https://freegeoip.net/json/' + domain, _.bind(function(response) {
      var json = JSON.parse(response);
      this.ip = json.ip;
      this.countryCode = json.country_code;
      this.countryName = json.country_name;
      this.regionCode = json.region_code;
      this.regionName = json.region_name;
      this.timezone = json.time_zone;
      this.zipcode = json.zip_code;
      this.city = json.city;
      this.lat = json.latitude;
      this.lng = json.longitude;
      console.log('Got remote geo, updating the relevant LogEntry');
      geoCache.removeEntry(cachedEntry);
      geoCache.addEntry(this);
      countryLog.addVisit(this.countryCode);
      this.storeEntries(logEntries);
    }, this));
  }
};

// Set up geo-cache

var GeoCache = function() {
  this.reset();
  this.addOwnLocation();
};

GeoCache.prototype.addOwnLocation = function(entry) {
  var ownGeoData = {
    ownGeoData: true
  };

  var entry = entry;
  var url = 'https://freegeoip.net/json'

  utils.get(url, _.bind(function(response) {
    if (response) {
      var json = JSON.parse(response);
      ownGeoData.ownIp = json.ip;
      ownGeoData.ownCountryCode = json.country_code;
      ownGeoData.ownCountryName = json.country_name;
      ownGeoData.ownRegionCode = json.region_code;
      ownGeoData.ownRegionName = json.region_name;
      ownGeoData.ownTimezone = json.time_zone;
      ownGeoData.ownZipcode = json.zip_code;
      ownGeoData.ownCity = json.city;
      ownGeoData.ownLat = json.latitude;
      ownGeoData.ownLng = json.longitude;

      geoCache.addOwnLocationEntry(ownGeoData);
      if (entry) {
        entry.getOwnGeo();
      }

      // store this so that it’s available to the template
      storage.set({ ownGeoData: ownGeoData });

      console.log('Got own geo, caching it');
    } else {
      console.log('Can’t get own geo data');
    }
  }, ownGeoData));
};

GeoCache.prototype.getOwnLocation = function() {
  return this.hasEntry('ownGeoData', true);
};

GeoCache.prototype.addOwnLocationEntry = function(ownGeoData) {
  if (!ownGeoData) {
    return;
  }
  this.removeOwnLocation();
  this.addEntry(ownGeoData);
};

GeoCache.prototype.removeOwnLocation = function() {
  var ownLocation = this.getOwnLocation();
  if (ownLocation) {
    console.log('Removing old own location entry');
    this.removeEntry(ownLocation);
  }
};

GeoCache.prototype.hasEntry = function(property, value) {
  var cacheEntry = _.find(this.entries, function(entry) {
    if (entry) {
      return entry[property] === value;
    } else {
      return false;
    }
  });
  return cacheEntry;
};

GeoCache.prototype.addEntry = function(object) {
  console.log('Caching a new entry');
  this.entries.push(object);
  this.updateStorage();
};

GeoCache.prototype.removeEntry = function(object) {
  console.log('Removing an entry from cache');
  var index = this.entries.indexOf(object);
  if (index > -1) {
    this.entries.splice(index, 1);
  }
  this.updateStorage();
};

GeoCache.prototype.reset = function() {
  console.log('Resetting geo cache');
  this.entries = [];
  this.recoverFromStorage();
};

GeoCache.prototype.recoverFromStorage = function() {
  console.log('Getting geo cache from storage');
  storage.get('geoCache', _.bind(function(geoCache) {
    if (_.isEmpty(geoCache) || geoCache === undefined) {
      return;
    }
    this.entries = geoCache.geoCache;
  }, this));
};

GeoCache.prototype.updateStorage = function() {
  storage.set({ 'geoCache': this.entries });
};

// Create and instantiate a country log

var CountryLog = function() {
  console.log('Creating a new CountryLog');
  this.reset();
};

CountryLog.prototype.addVisit = function(country) {
  if (_.has(this.visits, country)) {
    this.visits[country]++;
  } else {
    this.visits[country] = 1;
  }
  this.updateStorage();
};

CountryLog.prototype.reset = function() {
  this.visits = {};
  this.recoverFromStorage();
};

CountryLog.prototype.updateStorage = function() {
  storage.set({ 'countryLog': this.visits });
};

CountryLog.prototype.recoverFromStorage = function() {
  storage.get('countryLog', _.bind(function(countryLog) {
    if (_.isEmpty(countryLog) || countryLog === undefined) {
      return;
    }
    this.visits = countryLog.countryLog;
  }, this));
};

var Storage = function() {

};

Storage.prototype.set = function(property, value) {
  chrome.storage.local.set({ property: value });
};

Storage.prototype.get = function(property, callback) {
  chrome.storage.local.get(property, callback);
};

var utils = new Utils();
var storage = new Storage();
var geoCache = new GeoCache();
var countryLog = new CountryLog();
var logEntries = [];

// Define and set up Chrome utils

var ChromeUtils = function() {};

ChromeUtils.prototype.getTabById = function(tabId, callback) {
  // we use a callback here because chrome.tabs.get is asynchronous
  chrome.tabs.get(tabId, callback);
};

var chromeUtils = new ChromeUtils();

// Fetch the stored log entries on load, so we can keep adding to them

chrome.storage.local.get('logEntries', function(entries) {
  if (entries && entries.logEntries) {
    var entries = entries.logEntries;
    logEntries = _.map(entries, function(entry) {
      var logEntry = new LogEntry();
      logEntry.fromJSON(JSON.parse(entry));
      return logEntry;
    });

    console.log('Fetched the stored log entries');
  }
});

// Respond to events

chrome.tabs.onUpdated.addListener(function(tabId) {
  chromeUtils.getTabById(tabId, utils.createLogEntry);
});

chrome.tabs.onCreated.addListener(function(tab) {
  utils.createLogEntry(tab);
});

// fires when an existing tab is selected
chrome.tabs.onActivated.addListener(function(activeInfo) {
  var tabId = activeInfo.tabId;
  chromeUtils.getTabById(tabId, utils.createLogEntry);
});

chrome.browserAction.onClicked.addListener(function(tab) {
  chrome.tabs.executeScript(null, { file: 'injected/browserAction.js' });
});

chrome.storage.onChanged.addListener(function(data) {
  if (data.logEntries || data.geoCache) {
    if (_.has(data.logEntries, 'newValue') || _.has(data.geoCache, 'newValue')) {
      return;
    }

    // if there are no values then it means we want to clear all history
    utils.reset();
  }
});

// we have to use Chrome’s messaging system because the page can’t find out its own tabId
chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
  if (request.activeTab) {
    sendResponse(sender.tab);
  } else if (request.allTabs) {
    var windowId = sender.tab.windowId;
    var senderObject = sender;

    // this has to use message sending back and forth
    // simple value sending to a callback fails
    chrome.tabs.query({ windowId: windowId }, function(tabs) {
      chrome.tabs.sendMessage(senderObject.tab.id, { tabs: tabs });
    });
  } else if (request.allLogEntries) {
    sendResponse(logEntries);
  } else if (request.countryLog) {
    sendResponse(countryLog);
  }
});
